### ISSUE TITLE
Monitoring on SQL Server 2016 Std

### ISSUE THREAD

**Issue by PhilippZumdohme** [glensmall/SQL-Live-Monitor#1]
Hello,

we were trying to use the tool on a SQL Server 2016 Std Cluster, but when we use the tool it "breaks", and shows the attached error message.
The tools seems to connect if we ignore this, but does not fetch data.

![image](https://user-images.githubusercontent.com/30431803/28562810-09863468-7124-11e7-85e8-5de0025f1153.png)

**Comment by glensmall** [comment]
Thanks for this.  I thought when I had transferred from codeplex I had uploaded the 2016 compatible version but looks like I didn't.  I've just patched and pushed the code fix along with an updated binary which I tested on my local 2016 instance.  Hopefully that will fix your issue

**Comment by PhilippZumdohme** [comment]
Thanks, works like a charm.
Issue closed!
